name = "yearaway"
compatibility_date = "2024-01-01"

[env.production]
name = "yearaway"

[env.development]
name = "yearaway-dev"

# Build configuration
[build]
command = "./build.sh"
cwd = "."
watch_dir = "."

# Pages configuration
[[pages_builds]]
build_command = "./build.sh"
build_output_dir = "."
